package model;
// Generated Jul 20, 2023 7:38:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Baitap generated by hbm2java
 */
@Entity
@Table(name = "baitap", catalog = "toeic")
public class Baitap implements java.io.Serializable {

	private int maBt;
	private String cauHoi;
	private String goiY;
	private String dapAn;
	private int diemSo;
	private Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps = new HashSet<Taikhoanthuchienbaitap>(0);

	public Baitap() {
	}

	public Baitap(int maBt, String cauHoi, String goiY, String dapAn, int diemSo) {
		this.maBt = maBt;
		this.cauHoi = cauHoi;
		this.goiY = goiY;
		this.dapAn = dapAn;
		this.diemSo = diemSo;
	}

	public Baitap(int maBt, String cauHoi, String goiY, String dapAn, int diemSo,
			Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps) {
		this.maBt = maBt;
		this.cauHoi = cauHoi;
		this.goiY = goiY;
		this.dapAn = dapAn;
		this.diemSo = diemSo;
		this.taikhoanthuchienbaitaps = taikhoanthuchienbaitaps;
	}

	@Id

	@Column(name = "MaBT", unique = true, nullable = false)
	public int getMaBt() {
		return this.maBt;
	}

	public void setMaBt(int maBt) {
		this.maBt = maBt;
	}

	@Column(name = "CauHoi", nullable = false, length = 150)
	public String getCauHoi() {
		return this.cauHoi;
	}

	public void setCauHoi(String cauHoi) {
		this.cauHoi = cauHoi;
	}

	@Column(name = "GoiY", nullable = false, length = 50)
	public String getGoiY() {
		return this.goiY;
	}

	public void setGoiY(String goiY) {
		this.goiY = goiY;
	}

	@Column(name = "DapAn", nullable = false, length = 50)
	public String getDapAn() {
		return this.dapAn;
	}

	public void setDapAn(String dapAn) {
		this.dapAn = dapAn;
	}

	@Column(name = "DiemSo", nullable = false)
	public int getDiemSo() {
		return this.diemSo;
	}

	public void setDiemSo(int diemSo) {
		this.diemSo = diemSo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baitap")
	public Set<Taikhoanthuchienbaitap> getTaikhoanthuchienbaitaps() {
		return this.taikhoanthuchienbaitaps;
	}

	public void setTaikhoanthuchienbaitaps(Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps) {
		this.taikhoanthuchienbaitaps = taikhoanthuchienbaitaps;
	}

}
