package model;
// Generated Jul 20, 2023 7:38:23 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phanhoi generated by hbm2java
 */
@Entity
@Table(name = "phanhoi", catalog = "toeic")
public class Phanhoi implements java.io.Serializable {

	private Integer maPh;
	private Taikhoan taikhoan;
	private String tieuDe;
	private String noiDung;

	public Phanhoi() {
	}

	public Phanhoi(Taikhoan taikhoan, String tieuDe, String noiDung) {
		this.taikhoan = taikhoan;
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaPH", unique = true, nullable = false)
	public Integer getMaPh() {
		return this.maPh;
	}

	public void setMaPh(Integer maPh) {
		this.maPh = maPh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "TieuDe", nullable = false, length = 30)
	public String getTieuDe() {
		return this.tieuDe;
	}

	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}

	@Column(name = "NoiDung", nullable = false, length = 150)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
