package model;
// Generated Jul 30, 2023 7:12:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaikhoanthuchienbaitapId generated by hbm2java
 */
@Embeddable
public class TaikhoanthuchienbaitapId implements java.io.Serializable {

	private int maTk;
	private int maBt;

	public TaikhoanthuchienbaitapId() {
	}

	public TaikhoanthuchienbaitapId(int maTk, int maBt) {
		this.maTk = maTk;
		this.maBt = maBt;
	}

	@Column(name = "MaTK", nullable = false)
	public int getMaTk() {
		return this.maTk;
	}

	public void setMaTk(int maTk) {
		this.maTk = maTk;
	}

	@Column(name = "MaBT", nullable = false)
	public int getMaBt() {
		return this.maBt;
	}

	public void setMaBt(int maBt) {
		this.maBt = maBt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaikhoanthuchienbaitapId))
			return false;
		TaikhoanthuchienbaitapId castOther = (TaikhoanthuchienbaitapId) other;

		return (this.getMaTk() == castOther.getMaTk()) && (this.getMaBt() == castOther.getMaBt());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaTk();
		result = 37 * result + this.getMaBt();
		return result;
	}

}
