package model;
// Generated Jul 20, 2023 7:38:23 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taikhoanthuchienbaitap generated by hbm2java
 */
@Entity
@Table(name = "taikhoanthuchienbaitap", catalog = "toeic")
public class Taikhoanthuchienbaitap implements java.io.Serializable {

	private TaikhoanthuchienbaitapId id;
	private Baitap baitap;
	private Taikhoan taikhoan;
	private Date ngayTh;
	private Set<Taikhoancoxephang> taikhoancoxephangs = new HashSet<Taikhoancoxephang>(0);

	public Taikhoanthuchienbaitap() {
	}

	public Taikhoanthuchienbaitap(TaikhoanthuchienbaitapId id, Baitap baitap, Taikhoan taikhoan, Date ngayTh) {
		this.id = id;
		this.baitap = baitap;
		this.taikhoan = taikhoan;
		this.ngayTh = ngayTh;
	}

	public Taikhoanthuchienbaitap(TaikhoanthuchienbaitapId id, Baitap baitap, Taikhoan taikhoan, Date ngayTh,
			Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.id = id;
		this.baitap = baitap;
		this.taikhoan = taikhoan;
		this.ngayTh = ngayTh;
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maTk", column = @Column(name = "MaTK", nullable = false)),
			@AttributeOverride(name = "maBt", column = @Column(name = "MaBT", nullable = false)) })
	public TaikhoanthuchienbaitapId getId() {
		return this.id;
	}

	public void setId(TaikhoanthuchienbaitapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaBT", nullable = false, insertable = false, updatable = false)
	public Baitap getBaitap() {
		return this.baitap;
	}

	public void setBaitap(Baitap baitap) {
		this.baitap = baitap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayTH", nullable = false, length = 10)
	public Date getNgayTh() {
		return this.ngayTh;
	}

	public void setNgayTh(Date ngayTh) {
		this.ngayTh = ngayTh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoanthuchienbaitap")
	public Set<Taikhoancoxephang> getTaikhoancoxephangs() {
		return this.taikhoancoxephangs;
	}

	public void setTaikhoancoxephangs(Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

}
