package model;
// Generated Aug 21, 2023 3:25:15 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "toeic")
public class Taikhoan implements java.io.Serializable {

	private String maTk;
	private String tenTk;
	private String matKhauTk;
	private boolean quyenHan;
	private String hoTen;
	private Date namSinh;
	private String gioiTinh;
	private String queQuan;
	private String email;
	private Set<Phanhoi> phanhois = new HashSet<Phanhoi>(0);
	private Set<Taikhoanthuchienchude> taikhoanthuchienchudes = new HashSet<Taikhoanthuchienchude>(0);

	public Taikhoan() {
	}

	public Taikhoan(String maTk, String tenTk, String matKhauTk, boolean quyenHan, String hoTen, Date namSinh,
			String gioiTinh, String queQuan, String email) {
		this.maTk = maTk;
		this.tenTk = tenTk;
		this.matKhauTk = matKhauTk;
		this.quyenHan = quyenHan;
		this.hoTen = hoTen;
		this.namSinh = namSinh;
		this.gioiTinh = gioiTinh;
		this.queQuan = queQuan;
		this.email = email;
	}

	public Taikhoan(String maTk, String tenTk, String matKhauTk, boolean quyenHan, String hoTen, Date namSinh,
			String gioiTinh, String queQuan, String email, Set<Phanhoi> phanhois,
			Set<Taikhoanthuchienchude> taikhoanthuchienchudes) {
		this.maTk = maTk;
		this.tenTk = tenTk;
		this.matKhauTk = matKhauTk;
		this.quyenHan = quyenHan;
		this.hoTen = hoTen;
		this.namSinh = namSinh;
		this.gioiTinh = gioiTinh;
		this.queQuan = queQuan;
		this.email = email;
		this.phanhois = phanhois;
		this.taikhoanthuchienchudes = taikhoanthuchienchudes;
	}

	@Id

	@Column(name = "MaTK", unique = true, nullable = false, length = 10)
	public String getMaTk() {
		return this.maTk;
	}

	public void setMaTk(String maTk) {
		this.maTk = maTk;
	}

	@Column(name = "TenTK", nullable = false, length = 30)
	public String getTenTk() {
		return this.tenTk;
	}

	public void setTenTk(String tenTk) {
		this.tenTk = tenTk;
	}

	@Column(name = "MatKhauTK", nullable = false, length = 30)
	public String getMatKhauTk() {
		return this.matKhauTk;
	}

	public void setMatKhauTk(String matKhauTk) {
		this.matKhauTk = matKhauTk;
	}

	@Column(name = "QuyenHan", nullable = false)
	public boolean isQuyenHan() {
		return this.quyenHan;
	}

	public void setQuyenHan(boolean quyenHan) {
		this.quyenHan = quyenHan;
	}

	@Column(name = "HoTen", nullable = false, length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NamSinh", nullable = false, length = 10)
	public Date getNamSinh() {
		return this.namSinh;
	}

	public void setNamSinh(Date namSinh) {
		this.namSinh = namSinh;
	}

	@Column(name = "GioiTinh", nullable = false, length = 5)
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "QueQuan", nullable = false, length = 150)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Phanhoi> getPhanhois() {
		return this.phanhois;
	}

	public void setPhanhois(Set<Phanhoi> phanhois) {
		this.phanhois = phanhois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Taikhoanthuchienchude> getTaikhoanthuchienchudes() {
		return this.taikhoanthuchienchudes;
	}

	public void setTaikhoanthuchienchudes(Set<Taikhoanthuchienchude> taikhoanthuchienchudes) {
		this.taikhoanthuchienchudes = taikhoanthuchienchudes;
	}

}
