package model;
// Generated Jul 20, 2023 7:38:23 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "toeic")
public class Taikhoan implements java.io.Serializable {

	private Integer maTk;
	private String tenTk;
	private String matKhauTk;
	private boolean quyenHan;
	private Date namSinh;
	private boolean gioiTinh;
	private String queQuan;
	private Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps = new HashSet<Taikhoanthuchienbaitap>(0);
	private Set<Phanhoi> phanhois = new HashSet<Phanhoi>(0);
	private Set<Taikhoanthuchienchude> taikhoanthuchienchudes = new HashSet<Taikhoanthuchienchude>(0);

	public Taikhoan() {
	}

	public Taikhoan(String tenTk, String matKhauTk, boolean quyenHan, Date namSinh, boolean gioiTinh, String queQuan) {
		this.tenTk = tenTk;
		this.matKhauTk = matKhauTk;
		this.quyenHan = quyenHan;
		this.namSinh = namSinh;
		this.gioiTinh = gioiTinh;
		this.queQuan = queQuan;
	}

	public Taikhoan(String tenTk, String matKhauTk, boolean quyenHan, Date namSinh, boolean gioiTinh, String queQuan,
			Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps, Set<Phanhoi> phanhois,
			Set<Taikhoanthuchienchude> taikhoanthuchienchudes) {
		this.tenTk = tenTk;
		this.matKhauTk = matKhauTk;
		this.quyenHan = quyenHan;
		this.namSinh = namSinh;
		this.gioiTinh = gioiTinh;
		this.queQuan = queQuan;
		this.taikhoanthuchienbaitaps = taikhoanthuchienbaitaps;
		this.phanhois = phanhois;
		this.taikhoanthuchienchudes = taikhoanthuchienchudes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaTK", unique = true, nullable = false)
	public Integer getMaTk() {
		return this.maTk;
	}

	public void setMaTk(Integer maTk) {
		this.maTk = maTk;
	}

	@Column(name = "TenTK", nullable = false, length = 30)
	public String getTenTk() {
		return this.tenTk;
	}

	public void setTenTk(String tenTk) {
		this.tenTk = tenTk;
	}

	@Column(name = "MatKhauTK", nullable = false, length = 30)
	public String getMatKhauTk() {
		return this.matKhauTk;
	}

	public void setMatKhauTk(String matKhauTk) {
		this.matKhauTk = matKhauTk;
	}

	@Column(name = "QuyenHan", nullable = false)
	public boolean isQuyenHan() {
		return this.quyenHan;
	}

	public void setQuyenHan(boolean quyenHan) {
		this.quyenHan = quyenHan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NamSinh", nullable = false, length = 10)
	public Date getNamSinh() {
		return this.namSinh;
	}

	public void setNamSinh(Date namSinh) {
		this.namSinh = namSinh;
	}

	@Column(name = "GioiTinh", nullable = false)
	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "QueQuan", nullable = false, length = 150)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Taikhoanthuchienbaitap> getTaikhoanthuchienbaitaps() {
		return this.taikhoanthuchienbaitaps;
	}

	public void setTaikhoanthuchienbaitaps(Set<Taikhoanthuchienbaitap> taikhoanthuchienbaitaps) {
		this.taikhoanthuchienbaitaps = taikhoanthuchienbaitaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Phanhoi> getPhanhois() {
		return this.phanhois;
	}

	public void setPhanhois(Set<Phanhoi> phanhois) {
		this.phanhois = phanhois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Taikhoanthuchienchude> getTaikhoanthuchienchudes() {
		return this.taikhoanthuchienchudes;
	}

	public void setTaikhoanthuchienchudes(Set<Taikhoanthuchienchude> taikhoanthuchienchudes) {
		this.taikhoanthuchienchudes = taikhoanthuchienchudes;
	}

}
