package model;
// Generated Aug 21, 2023 3:25:15 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaikhoanthuchienchudeId generated by hbm2java
 */
@Embeddable
public class TaikhoanthuchienchudeId implements java.io.Serializable {

	private String maTk;
	private String maCd;

	public TaikhoanthuchienchudeId() {
	}

	public TaikhoanthuchienchudeId(String maTk, String maCd) {
		this.maTk = maTk;
		this.maCd = maCd;
	}

	@Column(name = "MaTK", nullable = false, length = 10)
	public String getMaTk() {
		return this.maTk;
	}

	public void setMaTk(String maTk) {
		this.maTk = maTk;
	}

	@Column(name = "MaCD", nullable = false, length = 10)
	public String getMaCd() {
		return this.maCd;
	}

	public void setMaCd(String maCd) {
		this.maCd = maCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaikhoanthuchienchudeId))
			return false;
		TaikhoanthuchienchudeId castOther = (TaikhoanthuchienchudeId) other;

		return ((this.getMaTk() == castOther.getMaTk()) || (this.getMaTk() != null && castOther.getMaTk() != null
				&& this.getMaTk().equals(castOther.getMaTk())))
				&& ((this.getMaCd() == castOther.getMaCd()) || (this.getMaCd() != null && castOther.getMaCd() != null
						&& this.getMaCd().equals(castOther.getMaCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaTk() == null ? 0 : this.getMaTk().hashCode());
		result = 37 * result + (getMaCd() == null ? 0 : this.getMaCd().hashCode());
		return result;
	}

}
