package model;
// Generated Jul 30, 2023 7:12:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xephang generated by hbm2java
 */
@Entity
@Table(name = "xephang", catalog = "toeic")
public class Xephang implements java.io.Serializable {

	private Integer maXh;
	private String tenXh;
	private Set<Taikhoancoxephang> taikhoancoxephangs = new HashSet<Taikhoancoxephang>(0);

	public Xephang() {
	}

	public Xephang(String tenXh) {
		this.tenXh = tenXh;
	}

	public Xephang(String tenXh, Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.tenXh = tenXh;
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaXH", unique = true, nullable = false)
	public Integer getMaXh() {
		return this.maXh;
	}

	public void setMaXh(Integer maXh) {
		this.maXh = maXh;
	}

	@Column(name = "TenXH", nullable = false, length = 30)
	public String getTenXh() {
		return this.tenXh;
	}

	public void setTenXh(String tenXh) {
		this.tenXh = tenXh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xephang")
	public Set<Taikhoancoxephang> getTaikhoancoxephangs() {
		return this.taikhoancoxephangs;
	}

	public void setTaikhoancoxephangs(Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

}
