package model;
// Generated Jul 20, 2023 7:38:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xephang generated by hbm2java
 */
@Entity
@Table(name = "xephang", catalog = "toeic")
public class Xephang implements java.io.Serializable {

	private int maXh;
	private String tenXh;
	private Set<Taikhoancoxephang> taikhoancoxephangs = new HashSet<Taikhoancoxephang>(0);

	public Xephang() {
	}

	public Xephang(int maXh, String tenXh) {
		this.maXh = maXh;
		this.tenXh = tenXh;
	}

	public Xephang(int maXh, String tenXh, Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.maXh = maXh;
		this.tenXh = tenXh;
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

	@Id

	@Column(name = "MaXH", unique = true, nullable = false)
	public int getMaXh() {
		return this.maXh;
	}

	public void setMaXh(int maXh) {
		this.maXh = maXh;
	}

	@Column(name = "TenXH", nullable = false, length = 30)
	public String getTenXh() {
		return this.tenXh;
	}

	public void setTenXh(String tenXh) {
		this.tenXh = tenXh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xephang")
	public Set<Taikhoancoxephang> getTaikhoancoxephangs() {
		return this.taikhoancoxephangs;
	}

	public void setTaikhoancoxephangs(Set<Taikhoancoxephang> taikhoancoxephangs) {
		this.taikhoancoxephangs = taikhoancoxephangs;
	}

}
